server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

app:
  imagekit:
    private-key:  ${IMAGEKIT_PRIVATE_KEY:}
    public-key:   ${IMAGEKIT_PUBLIC_KEY:}
    url-endpoint: ${IMAGEKIT_URL_ENDPOINT:}
  tmdb:
    api-key:     ${TMDB_API_KEY:}
    base-url:    https://api.themoviedb.org/3
    image-base:  https://image.tmdb.org/t/p/w500
    language:    id-ID